### ISSUE TITLE
DB_SLL_MODE 环境变量无效

### ISSUE THREAD

**Issue by amakerlife** [alist-org/alist-replit#13]
已正确配置 DB_SLL_MODE，但控制台输出报错，未识别到该变量

![image](https://user-images.githubusercontent.com/64350662/211232599-053b0ebc-7bdb-48a4-b09d-c274a9b7d024.png)

**Comment by jhihyulin** [comment]
是`DB_SSL_MODE`不是`DB_SLL_MODE`

**Comment by shaojs321** [comment]
哈哈  我也遇到这问题 作者可能手误

**Comment by amakerlife** [comment]
> 是`DB_SSL_MODE`不是`DB_SLL_MODE`

当时配置的时候也没认真看，直接改的配置文件😂
