### ISSUE TITLE
隔一段时间要更新 Refresh Token ，不然进不去

### ISSUE THREAD

**Issue by yangbe** [alist-org/alist-replit#22]
1、使用阿里云OPEN挂载的

2、隔段时间要更新一下Refresh Token才能正常使用，不然会出现下面的情况
<img width="354" alt="image" src="https://user-images.githubusercontent.com/9880101/227683750-3b24a642-2905-4243-9a66-acb4aa5f568e.png">

**Comment by Learnmore-knowledge** [comment]
![image](https://user-images.githubusercontent.com/125807789/227701043-58e129cb-7207-44cc-a18b-44968e9610cb.png)
目前用repilt 运行alist后 后台能够打开但是挂载阿里云盘等网盘后一直显示验证超时，其他方式挂载都没有问题
