### ISSUE TITLE
使用该服务请注意隐私安全

### ISSUE THREAD

**Issue by sxjeru** [alist-org/alist-replit#7]
若按照免费计划，其生成的数据库是**公开**的，为了安全请务必连接到其他私人数据库。

此外该服务唤醒速度较慢。
![image](https://user-images.githubusercontent.com/20513115/185051030-a555f2fd-684f-4a73-9a18-f606f4cd72d9.png)

**Comment by Vercharon** [comment]
Use [remote database](https://github.com/alist-org/alist-replit#database) like planetscale rather than replit's database. You can deploy Uptime-Kuma or buy hacker plan to keep your Repl always on.

**Comment by Jev121** [comment]
> Use [remote database](https://github.com/alist-org/alist-replit#database) like planetscale rather than replit's database. You can deploy Uptime-Kuma or buy hacker plan to keep your Repl always on.

我在replit上部署，连接Planetscale，一直报错，大概是SSL的原因，请问一下。连接Planetscale的话，System environment variables 如何编辑

**Comment by asong2022** [comment]
请问下按照攻略用的https://db4free.net/里的数据库，这样子数据安全吗

**Comment by sxjeru** [comment]
> 请问下按照攻略用的[https://db4free.net/](https://db4free.net/%E9%87%8C%E7%9A%84%E6%95%B0%E6%8D%AE%E5%BA%93%EF%BC%8C%E8%BF%99%E6%A0%B7%E5%AD%90%E6%95%B0%E6%8D%AE%E5%AE%89%E5%85%A8%E5%90%97)里的数据库，这样子数据安全吗

这样可以做到不被随意访问，但也请做好备份工作。
![image](https://user-images.githubusercontent.com/20513115/208302315-3ebc060d-03a7-4f51-9496-97531cea4215.png)

**Comment by asong2022** [comment]
> 
谢谢！！alist的配置我备份好了，文件应该都是在网盘上的。
还想请问下
https://db4free.net/
https://remotemysql.com/
https://www.freesqldatabase.com/
https://bit.io/
https://www.elephantsql.com/
https://scalingo.com/
http://cloud.yugabyte.com/
这几个中那个数据库加载的快一点呀，我现在用https://db4free.net/，感觉转圈转太慢了。

**Comment by sxjeru** [comment]
@asong2022 咱目前在用 bit.io，感觉速度还可以。并且那个是可以免费用作生产的，数据可靠性会高一些。

**Comment by asong2022** [comment]
> @asong2022 咱目前在用 bit.io，感觉速度还可以。并且那个是可以免费用作生产的，数据可靠性会高一些。
bit.io的
{
>   "DB_TYPE":"mysql",
>   "DB_HOST":"sql.com",
>   "DB_PORT":"3306",
>   "DB_USER":"alist",
>   "DB_PASS":"password",
>   "DB_NAME":"alist",
>   "DB_TABLE_PREFIX":"alist_",
>   "DB_SLL_MODE":"true"
> }
怎么填呀，我填了没反应

**Comment by sxjeru** [comment]
@asong2022 `DB_TYPE`为 postgres，其他根据 Connect 页信息填写。

**Comment by asong2022** [comment]
@sxjeru 
```
{
  "DB_TYPE": "postgres",
  "DB_HOST": "db.bit.io",
  "DB_PORT": "5432",
  "DB_USER": "asong2022",
  "DB_PASS": "v2_3xLCw_23mSwGaJiaKV5ihMJgMQtJb",
  "DB_NAME": "asong2022/asong",
  "DB_TABLE_PREFIX": "alist_",
  "DB_SLL_MODE": "true"
}
```
我这样子了怎么还是不行呀~求大佬帮助

**Comment by sxjeru** [comment]
@asong2022 
~~DB_SLL_MODE 应该是 DB_SSL_MODE.~~
帮你试了一下，数据库能正常连接。调试正常后记得换掉公开的密码。

**Comment by asong2022** [comment]
@sxjeru 谢谢！！我是根据readme那个md文档复制的。

**Comment by asong2022** [comment]
我还是失败了……

**Comment by asong2022** [comment]
我还是失败了……

**Comment by asong2022** [comment]
我还是失败了……

**Comment by asong2022** [comment]
我还是失败了……

**Comment by asong2022** [comment]
```
 bash main.sh
INFO[2022-12-25 02:41:58] reading config file: data/config.json        
INFO[2022-12-25 02:41:58] load config from env with prefix:            
INFO[2022-12-25 02:41:58] init logrus...                               
exit status 1
```

**Comment by sxjeru** [comment]
@asong2022 问一下你的配置项是加在哪儿的？如果是配置文件里，那格式可不是“DB_TYPE”这样的，这是加在环境变量里的。
参考文档：https://alist.nn.ci/zh/config/configuration.html

**Comment by asong2022** [comment]
@sxjeru  
![image](https://user-images.githubusercontent.com/118357167/209456276-a7ed4b67-60cb-46c3-846b-1c550b3084ad.png)

**Comment by asong2022** [comment]
我是按照说明来加的，Switch to secrets tab then edit raw json。

**Comment by sxjeru** [comment]
@asong2022 抱歉，咱可能帮不了你了。先把 DB_SSL_MODE 还原成 DB_SLL_MODE 吧。
我在文档里找不到环境变量相关资料，我目前也没在用 Replit 部署。
还是麻烦请教开发者相关人员吧。

**Comment by asong2022** [comment]
@sxjeru  您是在哪里部署的呀~

**Comment by sxjeru** [comment]
> @sxjeru 您是在哪里部署的呀~

试用了各种 PaaS，最后还是去买了个vps部署，既简单又有效。
如果没有条件，可以去看看 [Koyeb](https://github.com/alist-org/alist-koyeb).

**Comment by asong2022** [comment]
@sxjeru vps您推荐哪个呀有指路吗

**Comment by sxjeru** [comment]
> @sxjeru vps您推荐哪个呀有指路吗

唔没有推荐，国内也就那几个云自己看着选吧，应该差不太多。

**Comment by asong2022** [comment]
@sxjeru 谢谢！那几个云我只看到了轻量服务器耶，没看到vps

**Comment by sxjeru** [comment]
> @sxjeru 谢谢！那几个云我只看到了轻量服务器耶，没看到vps

az，服务器就是 vps 的说。轻量服务器适合低负载业务。

**Comment by asong2022** [comment]
@sxjeru 谢谢！！

**Comment by oopstls** [comment]
🤔有点没弄懂，数据库是公开的，配置文件也是公开的吧，私人数据库链接方式写在配置文件里的话，不就也不安全了吗。

**Comment by sxjeru** [comment]
> 🤔有点没弄懂，数据库是公开的，配置文件也是公开的吧，私人数据库链接方式写在配置文件里的话，不就也不安全了吗。

可以写在环境变量里，那个是不公开的。可参考本仓库 README.
Tools -> Secrets

**Comment by oopstls** [comment]
> 

喔喔，懂了 感谢
